"""Initial migration

Revision ID: 28c6bde271fe
Revises: 
Create Date: 2026-07-10 12:53:54.179929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c6bde271fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_bank_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_holder_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('ifsc_code', sa.String(), nullable=False),
    sa.Column('upi_id', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('target_user_ids', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_bank_details_id'), 'admin_bank_details', ['id'], unique=False)
    op.create_table('admin_fcm_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_fcm_tokens_id'), 'admin_fcm_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_admin_fcm_tokens_token'), 'admin_fcm_tokens', ['token'], unique=True)
    op.create_table('arrow_contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('entry_fee', sa.Float(), nullable=False),
    sa.Column('total_slots', sa.Integer(), nullable=False),
    sa.Column('joined_slots', sa.Integer(), nullable=True),
    sa.Column('prize_pool', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('prize_rules', sa.String(), nullable=False),
    sa.Column('grid_size', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('arrow_count', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arrow_contests_id'), 'arrow_contests', ['id'], unique=False)
    op.create_table('blackjack_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_bet', sa.Float(), nullable=True),
    sa.Column('max_bet', sa.Float(), nullable=True),
    sa.Column('winning_percentage', sa.Float(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blackjack_settings_id'), 'blackjack_settings', ['id'], unique=False)
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('entry_fee', sa.Float(), nullable=False),
    sa.Column('total_slots', sa.Integer(), nullable=False),
    sa.Column('joined_slots', sa.Integer(), nullable=True),
    sa.Column('prize_pool', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('prize_rules', sa.String(), nullable=True),
    sa.Column('questions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contests_id'), 'contests', ['id'], unique=False)
    op.create_table('fruit_contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('entry_fee', sa.Float(), nullable=False),
    sa.Column('total_slots', sa.Integer(), nullable=False),
    sa.Column('joined_slots', sa.Integer(), nullable=True),
    sa.Column('prize_pool', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('prize_rules', sa.String(), nullable=False),
    sa.Column('seed', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fruit_contests_id'), 'fruit_contests', ['id'], unique=False)
    op.create_table('fruit_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_bet', sa.Float(), nullable=True),
    sa.Column('max_bet', sa.Float(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('winning_percentage', sa.Float(), nullable=True),
    sa.Column('multipliers_json', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fruit_settings_id'), 'fruit_settings', ['id'], unique=False)
    op.create_table('image_puzzle_contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('entry_fee', sa.Float(), nullable=False),
    sa.Column('total_slots', sa.Integer(), nullable=False),
    sa.Column('joined_slots', sa.Integer(), nullable=True),
    sa.Column('prize_pool', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('prize_rules', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('grid_size', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_puzzle_contests_id'), 'image_puzzle_contests', ['id'], unique=False)
    op.create_table('lottery_draws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('ticket_price', sa.Float(), nullable=False),
    sa.Column('prize_pool', sa.Float(), nullable=False),
    sa.Column('draw_time', sa.DateTime(), nullable=False),
    sa.Column('max_tickets', sa.Integer(), nullable=True),
    sa.Column('joined_tickets', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('winning_number', sa.String(), nullable=True),
    sa.Column('win_percentage', sa.Float(), nullable=True),
    sa.Column('forced_winning_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lottery_draws_id'), 'lottery_draws', ['id'], unique=False)
    op.create_table('mines_rtp_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mines_rtp_settings_id'), 'mines_rtp_settings', ['id'], unique=False)
    op.create_table('mines_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_edge', sa.Float(), nullable=True),
    sa.Column('min_bet', sa.Float(), nullable=True),
    sa.Column('max_bet', sa.Float(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mines_settings_id'), 'mines_settings', ['id'], unique=False)
    op.create_table('plinko_multipliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('multipliers_json', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plinko_multipliers_id'), 'plinko_multipliers', ['id'], unique=False)
    op.create_table('plinko_rtp_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('probability_json', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plinko_rtp_settings_id'), 'plinko_rtp_settings', ['id'], unique=False)
    op.create_table('plinko_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_bet', sa.Float(), nullable=True),
    sa.Column('max_bet', sa.Float(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plinko_settings_id'), 'plinko_settings', ['id'], unique=False)
    op.create_table('portfolio_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('contact_address', sa.String(), nullable=True),
    sa.Column('office_hours', sa.String(), nullable=True),
    sa.Column('apk_link', sa.String(), nullable=True),
    sa.Column('web_app_link', sa.String(), nullable=True),
    sa.Column('telegram_link', sa.String(), nullable=True),
    sa.Column('instagram_link', sa.String(), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=True),
    sa.Column('add_amount_method', sa.String(), nullable=False),
    sa.Column('admin_upi_id', sa.String(), nullable=True),
    sa.Column('admin_bank_holder', sa.String(), nullable=True),
    sa.Column('admin_bank_name', sa.String(), nullable=True),
    sa.Column('admin_bank_account', sa.String(), nullable=True),
    sa.Column('admin_bank_ifsc', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_configs_id'), 'portfolio_configs', ['id'], unique=False)
    op.create_table('portfolio_contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_contact_messages_id'), 'portfolio_contact_messages', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('options', sa.String(), nullable=False),
    sa.Column('correct_answer_index', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_language'), 'questions', ['language'], unique=False)
    op.create_table('rtp_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=False),
    sa.Column('probability_json', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rtp_settings_id'), 'rtp_settings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=False),
    sa.Column('referred_by', sa.String(), nullable=True),
    sa.Column('deposit_balance', sa.Float(), nullable=True),
    sa.Column('winning_balance', sa.Float(), nullable=True),
    sa.Column('bonus_balance', sa.Float(), nullable=True),
    sa.Column('kyc_status', sa.String(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('fcm_token', sa.String(), nullable=True),
    sa.Column('device_details', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('plinko_bet_count', sa.Integer(), nullable=True),
    sa.Column('bank_account_number', sa.String(), nullable=True),
    sa.Column('bank_ifsc_code', sa.String(), nullable=True),
    sa.Column('bank_account_holder_name', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('word_contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('entry_fee', sa.Float(), nullable=False),
    sa.Column('total_slots', sa.Integer(), nullable=False),
    sa.Column('joined_slots', sa.Integer(), nullable=True),
    sa.Column('prize_pool', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('prize_rules', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_contests_id'), 'word_contests', ['id'], unique=False)
    op.create_table('arrow_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('completion_seconds', sa.Float(), nullable=False),
    sa.Column('moves', sa.Integer(), nullable=True),
    sa.Column('taps_sequence', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('device_fingerprint', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['arrow_contests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arrow_attempts_id'), 'arrow_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_arrow_attempts_session_id'), 'arrow_attempts', ['session_id'], unique=True)
    op.create_table('arrow_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('layout', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['arrow_contests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contest_id')
    )
    op.create_index(op.f('ix_arrow_games_id'), 'arrow_games', ['id'], unique=False)
    op.create_table('arrow_leaderboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('completion_seconds', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('prize_amount', sa.Float(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['arrow_contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arrow_leaderboards_id'), 'arrow_leaderboards', ['id'], unique=False)
    op.create_table('arrow_puzzle_seeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['arrow_contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arrow_puzzle_seeds_id'), 'arrow_puzzle_seeds', ['id'], unique=False)
    op.create_table('blackjack_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bet_amount', sa.Float(), nullable=False),
    sa.Column('is_split', sa.Boolean(), nullable=True),
    sa.Column('split_bet_amount', sa.Float(), nullable=True),
    sa.Column('player_hand_1', sa.String(), nullable=False),
    sa.Column('player_hand_2', sa.String(), nullable=False),
    sa.Column('dealer_hand', sa.String(), nullable=False),
    sa.Column('current_hand_index', sa.Integer(), nullable=True),
    sa.Column('hand_1_status', sa.String(), nullable=True),
    sa.Column('hand_2_status', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('win_amount', sa.Float(), nullable=True),
    sa.Column('target_outcome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blackjack_games_id'), 'blackjack_games', ['id'], unique=False)
    op.create_table('contest_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('quiz_questions', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_participants_id'), 'contest_participants', ['id'], unique=False)
    op.create_table('fruit_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bet_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_multiplier', sa.Float(), nullable=True),
    sa.Column('win_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fruit_games_id'), 'fruit_games', ['id'], unique=False)
    op.create_table('fruit_leaderboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_combo', sa.Integer(), nullable=False),
    sa.Column('miss_count', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('prize_amount', sa.Float(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['fruit_contests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fruit_leaderboards_id'), 'fruit_leaderboards', ['id'], unique=False)
    op.create_table('fruit_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('device_fingerprint', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['fruit_contests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fruit_matches_id'), 'fruit_matches', ['id'], unique=False)
    op.create_index(op.f('ix_fruit_matches_session_id'), 'fruit_matches', ['session_id'], unique=True)
    op.create_table('image_puzzle_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('completion_seconds', sa.Float(), nullable=False),
    sa.Column('moves', sa.Integer(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=True),
    sa.Column('move_sequence', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('device_fingerprint', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['image_puzzle_contests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_puzzle_attempts_id'), 'image_puzzle_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_image_puzzle_attempts_session_id'), 'image_puzzle_attempts', ['session_id'], unique=True)
    op.create_table('image_puzzle_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('shuffled_layout', sa.String(), nullable=False),
    sa.Column('solution_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['image_puzzle_contests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contest_id')
    )
    op.create_index(op.f('ix_image_puzzle_games_id'), 'image_puzzle_games', ['id'], unique=False)
    op.create_table('image_puzzle_leaderboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('completion_seconds', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['image_puzzle_contests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_puzzle_leaderboard_id'), 'image_puzzle_leaderboard', ['id'], unique=False)
    op.create_table('lottery_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(), nullable=False),
    sa.Column('purchase_time', sa.DateTime(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('reward_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['draw_id'], ['lottery_draws.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_index(op.f('ix_lottery_tickets_id'), 'lottery_tickets', ['id'], unique=False)
    op.create_table('mines_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bet_amount', sa.Float(), nullable=False),
    sa.Column('mines_count', sa.Integer(), nullable=False),
    sa.Column('mines_positions', sa.String(), nullable=False),
    sa.Column('revealed_positions', sa.String(), nullable=True),
    sa.Column('current_multiplier', sa.Float(), nullable=True),
    sa.Column('current_win', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mines_games_id'), 'mines_games', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('data_json', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('plinko_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bet_amount', sa.Float(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('final_bucket', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('win_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plinko_games_id'), 'plinko_games', ['id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('bonus_given', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_user_id')
    )
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_table('spin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_payload', sa.String(), nullable=False),
    sa.Column('generated_result', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spin_audit_logs_id'), 'spin_audit_logs', ['id'], unique=False)
    op.create_table('spins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bet_amount', sa.Float(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('win_amount', sa.Float(), nullable=False),
    sa.Column('result_type', sa.String(), nullable=False),
    sa.Column('wheel_segment', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spins_id'), 'spins', ['id'], unique=False)
    op.create_table('user_question_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('served_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_question_history_id'), 'user_question_history', ['id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('utr', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utr')
    )
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_table('word_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('completion_time_seconds', sa.Float(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=True),
    sa.Column('wrong_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('device_fingerprint', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['word_contests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_attempts_id'), 'word_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_word_attempts_session_id'), 'word_attempts', ['session_id'], unique=True)
    op.create_table('word_leaderboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('completion_time_seconds', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('prize_amount', sa.Float(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['word_contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_leaderboards_id'), 'word_leaderboards', ['id'], unique=False)
    op.create_table('word_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('puzzle_data', sa.String(), nullable=False),
    sa.Column('clues', sa.String(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('points_reward', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['word_contests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_questions_id'), 'word_questions', ['id'], unique=False)
    op.create_table('fruit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('coordinates', sa.String(), nullable=True),
    sa.Column('sliced_items', sa.String(), nullable=True),
    sa.Column('points_delta', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['fruit_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fruit_events_id'), 'fruit_events', ['id'], unique=False)
    op.create_table('fruit_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('max_combo', sa.Integer(), nullable=True),
    sa.Column('miss_count', sa.Integer(), nullable=True),
    sa.Column('bomb_hit_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['fruit_contests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['match_id'], ['fruit_matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fruit_scores_id'), 'fruit_scores', ['id'], unique=False)
    op.create_table('word_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answer_submitted', sa.String(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=True),
    sa.Column('time_taken_seconds', sa.Float(), nullable=False),
    sa.Column('telemetry_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['word_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['word_questions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_answers_id'), 'word_answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_answers_id'), table_name='word_answers')
    op.drop_table('word_answers')
    op.drop_index(op.f('ix_fruit_scores_id'), table_name='fruit_scores')
    op.drop_table('fruit_scores')
    op.drop_index(op.f('ix_fruit_events_id'), table_name='fruit_events')
    op.drop_table('fruit_events')
    op.drop_index(op.f('ix_word_questions_id'), table_name='word_questions')
    op.drop_table('word_questions')
    op.drop_index(op.f('ix_word_leaderboards_id'), table_name='word_leaderboards')
    op.drop_table('word_leaderboards')
    op.drop_index(op.f('ix_word_attempts_session_id'), table_name='word_attempts')
    op.drop_index(op.f('ix_word_attempts_id'), table_name='word_attempts')
    op.drop_table('word_attempts')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_user_question_history_id'), table_name='user_question_history')
    op.drop_table('user_question_history')
    op.drop_index(op.f('ix_spins_id'), table_name='spins')
    op.drop_table('spins')
    op.drop_index(op.f('ix_spin_audit_logs_id'), table_name='spin_audit_logs')
    op.drop_table('spin_audit_logs')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_plinko_games_id'), table_name='plinko_games')
    op.drop_table('plinko_games')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_mines_games_id'), table_name='mines_games')
    op.drop_table('mines_games')
    op.drop_index(op.f('ix_lottery_tickets_id'), table_name='lottery_tickets')
    op.drop_table('lottery_tickets')
    op.drop_index(op.f('ix_image_puzzle_leaderboard_id'), table_name='image_puzzle_leaderboard')
    op.drop_table('image_puzzle_leaderboard')
    op.drop_index(op.f('ix_image_puzzle_games_id'), table_name='image_puzzle_games')
    op.drop_table('image_puzzle_games')
    op.drop_index(op.f('ix_image_puzzle_attempts_session_id'), table_name='image_puzzle_attempts')
    op.drop_index(op.f('ix_image_puzzle_attempts_id'), table_name='image_puzzle_attempts')
    op.drop_table('image_puzzle_attempts')
    op.drop_index(op.f('ix_fruit_matches_session_id'), table_name='fruit_matches')
    op.drop_index(op.f('ix_fruit_matches_id'), table_name='fruit_matches')
    op.drop_table('fruit_matches')
    op.drop_index(op.f('ix_fruit_leaderboards_id'), table_name='fruit_leaderboards')
    op.drop_table('fruit_leaderboards')
    op.drop_index(op.f('ix_fruit_games_id'), table_name='fruit_games')
    op.drop_table('fruit_games')
    op.drop_index(op.f('ix_contest_participants_id'), table_name='contest_participants')
    op.drop_table('contest_participants')
    op.drop_index(op.f('ix_blackjack_games_id'), table_name='blackjack_games')
    op.drop_table('blackjack_games')
    op.drop_index(op.f('ix_arrow_puzzle_seeds_id'), table_name='arrow_puzzle_seeds')
    op.drop_table('arrow_puzzle_seeds')
    op.drop_index(op.f('ix_arrow_leaderboards_id'), table_name='arrow_leaderboards')
    op.drop_table('arrow_leaderboards')
    op.drop_index(op.f('ix_arrow_games_id'), table_name='arrow_games')
    op.drop_table('arrow_games')
    op.drop_index(op.f('ix_arrow_attempts_session_id'), table_name='arrow_attempts')
    op.drop_index(op.f('ix_arrow_attempts_id'), table_name='arrow_attempts')
    op.drop_table('arrow_attempts')
    op.drop_index(op.f('ix_word_contests_id'), table_name='word_contests')
    op.drop_table('word_contests')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rtp_settings_id'), table_name='rtp_settings')
    op.drop_table('rtp_settings')
    op.drop_index(op.f('ix_questions_language'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_portfolio_contact_messages_id'), table_name='portfolio_contact_messages')
    op.drop_table('portfolio_contact_messages')
    op.drop_index(op.f('ix_portfolio_configs_id'), table_name='portfolio_configs')
    op.drop_table('portfolio_configs')
    op.drop_index(op.f('ix_plinko_settings_id'), table_name='plinko_settings')
    op.drop_table('plinko_settings')
    op.drop_index(op.f('ix_plinko_rtp_settings_id'), table_name='plinko_rtp_settings')
    op.drop_table('plinko_rtp_settings')
    op.drop_index(op.f('ix_plinko_multipliers_id'), table_name='plinko_multipliers')
    op.drop_table('plinko_multipliers')
    op.drop_index(op.f('ix_mines_settings_id'), table_name='mines_settings')
    op.drop_table('mines_settings')
    op.drop_index(op.f('ix_mines_rtp_settings_id'), table_name='mines_rtp_settings')
    op.drop_table('mines_rtp_settings')
    op.drop_index(op.f('ix_lottery_draws_id'), table_name='lottery_draws')
    op.drop_table('lottery_draws')
    op.drop_index(op.f('ix_image_puzzle_contests_id'), table_name='image_puzzle_contests')
    op.drop_table('image_puzzle_contests')
    op.drop_index(op.f('ix_fruit_settings_id'), table_name='fruit_settings')
    op.drop_table('fruit_settings')
    op.drop_index(op.f('ix_fruit_contests_id'), table_name='fruit_contests')
    op.drop_table('fruit_contests')
    op.drop_index(op.f('ix_contests_id'), table_name='contests')
    op.drop_table('contests')
    op.drop_index(op.f('ix_blackjack_settings_id'), table_name='blackjack_settings')
    op.drop_table('blackjack_settings')
    op.drop_index(op.f('ix_arrow_contests_id'), table_name='arrow_contests')
    op.drop_table('arrow_contests')
    op.drop_index(op.f('ix_admin_fcm_tokens_token'), table_name='admin_fcm_tokens')
    op.drop_index(op.f('ix_admin_fcm_tokens_id'), table_name='admin_fcm_tokens')
    op.drop_table('admin_fcm_tokens')
    op.drop_index(op.f('ix_admin_bank_details_id'), table_name='admin_bank_details')
    op.drop_table('admin_bank_details')
    # ### end Alembic commands ###
