// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6U2UqWTZbYZf1iNRqTAqyhpqyV3QSlDI',
    appId: '1:449225224080:web:c0404987a7860770bb8d15',
    messagingSenderId: '449225224080',
    projectId: 'dailyearn99-app-prod',
    authDomain: 'dailyearn99-app-prod.firebaseapp.com',
    storageBucket: 'dailyearn99-app-prod.firebasestorage.app',
    measurementId: 'G-BNDT4BY9E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO5Cly89WWTLYAYydXlqtUYLR4A987g4Q',
    appId: '1:449225224080:android:443ccbd1d546d579bb8d15',
    messagingSenderId: '449225224080',
    projectId: 'dailyearn99-app-prod',
    storageBucket: 'dailyearn99-app-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrjG6n751AwXSUvd4ixlCm2l0h-GoisX4',
    appId: '1:449225224080:ios:d2b86e85ac6aec84bb8d15',
    messagingSenderId: '449225224080',
    projectId: 'dailyearn99-app-prod',
    storageBucket: 'dailyearn99-app-prod.firebasestorage.app',
    iosBundleId: 'com.dailyearn99.dailyearn99',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrjG6n751AwXSUvd4ixlCm2l0h-GoisX4',
    appId: '1:449225224080:ios:01c1a08bc5b9035fbb8d15',
    messagingSenderId: '449225224080',
    projectId: 'dailyearn99-app-prod',
    storageBucket: 'dailyearn99-app-prod.firebasestorage.app',
    iosBundleId: 'com.dailyearn99.dailyearn99',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6U2UqWTZbYZf1iNRqTAqyhpqyV3QSlDI',
    appId: '1:449225224080:web:ea7a9c351471175dbb8d15',
    messagingSenderId: '449225224080',
    projectId: 'dailyearn99-app-prod',
    authDomain: 'dailyearn99-app-prod.firebaseapp.com',
    storageBucket: 'dailyearn99-app-prod.firebasestorage.app',
    measurementId: 'G-DQC7KQFTCG',
  );
}
